In [1]:
!pip install pymupdf 
!pip install contractions 
!pip install num2words
!pip install jiwer
#import num2words as n2w
import contractions as ctr
import pandas as pd
import pymupdf
import re
import string
import jiwer
from normalize_time_simple import normalize_times
#Set DF display option
pd.set_option('display.max_colwidth', None)

Requirement already satisfied: pymupdf in c:\users\khuong nguyen\anaconda3\lib\site-packages (1.27.2.3)
Requirement already satisfied: contractions in c:\users\khuong nguyen\anaconda3\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\khuong nguyen\anaconda3\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\khuong nguyen\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in c:\users\khuong nguyen\anaconda3\lib\site-packages (from textsearch>=0.0.21->contractions) (2.3.1)
Requirement already satisfied: num2words in c:\users\khuong nguyen\anaconda3\lib\site-packages (0.5.14)
Requirement already satisfied: docopt>=0.6.2 in c:\users\khuong nguyen\anaconda3\lib\site-packages (from num2words) (0.6.2)
Requirement already satisfied: jiwer in c:\users\khuong nguyen\anaconda3\lib\site-packages (4.0.0)
Requirement already satisfied: click>=8.1.8 in c:\users\khuong nguyen\anaconda3\lib\site-packages (from jiwer) (8.4.1)
Requirement already satisfied: rapidfuzz>=3.9.7 in c:\users\khuong nguyen\anaconda3\lib\site-packages (from jiwer) (3.14.5)
Requirement already satisfied: colorama in c:\users\khuong nguyen\anaconda3\lib\site-packages (from click>=8.1.8->jiwer) (0.4.6)

# 1. Extract Data from reference progress note (ASSUMED PDF) + Get Data from NurseGPT (assumed CSV file)

In [2]:
# Get refernce text:
#mapping_color_doc = pd.read_excel(r"C:\Users\Khuong Nguyen\Desktop\NurseGPT Eval\Automation Script\Simulate_Tier_Mapping_For_ProgressNote.xlsx")
#ref_notes = pymupdf.open(r"")
#hypo_notes = pd.read_csv(r"") #Assume NurseGPT's artifacts stored as csv/ xlsx

def reg_pattern_find(text, page_number):
    pattern_list = {
         "Reference Diagnoses": r"Diagnoses\s*:(.*?)(?=\n[A-Z][a-z]+\s*:|$)",
    }
    result = {}
    
    for field_name, pattern in pattern_list.items():
        match = re.search(pattern, text, re.DOTALL)
        if match:
            result[field_name] =  match.group(1) 
        else:
             result[field_name] = None
             print(f"Page {page_number+1} does not contain the pattern, please recheck this page content")
    return result 
             

# Extract content from PDFs -> Convert into DF

def note_extraction(note_doc, mapping_doc):
    rows = []
    for page_num, page in enumerate(note_doc, start = 1): #Loop through each progress note (1 note = 1 page)
        note_content = page.get_text() #Get ALL content fields (Diagnoses details, Date Created, Physicians ID,etc)
        note_type = mapping_color_doc.loc[mapping_color_doc['Page Number'] == page_num, 'Type'].values[0]
        
        field_results = reg_pattern_find(note_content, page_num)
        field_results["Page Number"] = page_num
        field_results['Note Type'] = note_type 
        rows.append(field_results)
        
        reference_note_df = pd.DataFrame(rows)
        
    return reference_note_df 



ref_notes = note_extraction(ref_notes, mapping_color_doc)
ref_notes

NameError: name 'ref_notes' is not defined

# 2. Data Preprocessing Steps

In [3]:
spoken_ref_note = pd.read_csv(r"C:\Users\Khuong Nguyen\Desktop\NurseGPT Eval\Automation Script\WER_Automation_Script\Data\nurse_spoken_script(Claude).csv", encoding='cp1252')
nurse_gpt_note = pd.read_excel(r"C:\Users\Khuong Nguyen\Desktop\NurseGPT Eval\Automation Script\WER_Automation_Script\Data\nurse_asr_transcription_for_WER_test.xlsx", index_col = False)

In [ ]:

def contraction(text):
    if isinstance(text, str):
        return ctr.fix(text)
    else:
        return text

def convert_number_words(match):
    number_str = match.group(0)
    number_int = int(number_str)
    return n2w.num2words(number_int)



def preprocessing_pipeline(df, column):
    df = df.copy()
    df[column] = df[column].str.lower()  # Decapitalization
    df[column] = df[column].str.replace('\n', ' ')  # Remove newline

    df[column] = df[column].apply(normalize_times)
    #df[column] = df[column].apply(lambda x: re.sub(r'\d+', convert_number_words, x) if isinstance(x, str) else x)


    df[column] = df[column].str.replace('-', ' ')
    df[column] = df[column].str.replace(':', ' ')
    df[column] = df[column].str.replace('/', 'over')
    df[column] = df[column].str.replace(r"'s\b", '', regex=True)
    # Contraction
    df[column] = df[column].apply(contraction)

    # Removal of punctuation
    punc_table = str.maketrans("", "", string.punctuation)
    df[column] = df[column].str.translate(punc_table)

    # Removal of white space
    df[column] = df[column].str.replace(r'\s+', ' ', regex=True)  # Extra white space
    df[column] = df[column].str.strip()  # Trailing white space

    return df

spoken_note_cleaned = preprocessing_pipeline(spoken_ref_note, 'Reference Diagnoses')
nurseGPT_transcript_cleaned = preprocessing_pipeline(nurse_gpt_note, 'Hypothesis Diagnoses')

In [5]:
spoken_note_cleaned

,Reference Diagnoses,Page Number,Type
0,at approximately 19 00 i responded to an emergency call bell near the third floor elevator upon arrival i found mrs jane doe that room number one twenty one eighty two years old lying on her back with a care aide supporting her head the care aide witnessed the fall and reported that the resident was reaching for the elevator button when she lost her balance and fell backward striking the back of her head on the tile floor mrs doe was alert but confused about what happened there was a three centimeter hematoma on the back of her head but no open wounds her glasgow coma scale was thirteen eye response four verbal response four and motor response five i checked her vitals blood pressure was one sixty over ninety heart rate eighty eight respiratory rate eighteen and oxygen saturation ninety six percent on room air i initiated neuro checks every fifteen minutes and gave her 06 00 fifty milligrams of tylenol per standing orders i paged the on call physician but did not get an immediate response since this was a witnessed fall with a head impact i called nine one one for hospital transfer i also notified mrs doe power of attorney that her husband george the resident was transferred to the hospital at seven thirty five pm along with her med administration record recent vitals and her advance directives i have let facility maintenance know to check the lighting in that elevator area i will follow up with the hospital for updates,1.0,Fall emergency
1,i found mrs jane doe on the floor by the third floor elevator after a witnessed fall she hit the back of her head on the floor she is awake but confused there is a three centimeter bump on the back of her head with no open cut her blood pressure is one sixty over ninety heart rate eighty eight breathing eighteen oxygen ninety six percent on room air i started neuro checks every fifteen minutes gave tylenol six fifty per standing order paged the doctor called nine one one and notified her husband george,2.0,Fall with a head injury
2,i did a routine morning check on mrs jane doe she is awake and knows where she is a little unsure of the time she looks comfortable her skin is warm dry and intact blood pressure one thirty two over seventy eight heart rate seventy two breathing sixteen temperature thirty six point eight oxygen ninety eight percent she had a normal bowel movement and is walking well with her walker no pain and no concerns,3.0,Routine morning check
3,recording vital signs for mrs jane doe blood pressure one twenty eight over seventy six heart rate seventy breathing sixteen temperature thirty six point seven oxygen ninety seven percent on room air she is comfortable with no complaints,4.0,Vital signs only
4,mrs jane doe has pain in both knees from her arthritis worse the last two days especially in the mornings she rates it six out of ten achy and stiff no swelling blood pressure one forty over eighty four heart rate seventy six temperature thirty six point seven oxygen ninety seven percent i gave acetaminophen six fifty per standing order used a warm compress and asked for a physiotherapy referral i notified her family and will check again in four hours,5.0,Knee pain
5,mrs jane doe is more short of breath than usual with little activity no chest pain or fever her oxygen is ninety one percent on room air down from ninety five yesterday breathing twenty two and a little labored with wheezing i gave ventolin two puffs with a spacer per order encouraged pursed lip breathing and paged the doctor i notified her family,6.0,Shortness of breath
6,a care aide found mrs jane doe unresponsive in her wheelchair by the first floor elevator pale and clammy she responded weakly to a sternal rub blood pressure ninety over sixty heart rate one twenty and irregular breathing twenty four oxygen ninety one percent i gave oxygen two liters by nasal cannula and her oxygen came up to ninety four i gave aspirin eighty one per order called the doctor and nine one one she is full code i notified her family,7.0,Found unresponsive
7,a care aide saw mrs jane doe unsteady by the second floor elevator while moving from her walker she is awake and knows where she is a little unsure of the time her walker was set too low with the brake half on she has good shoes and no pain blood pressure one thirty eight over eighty two heart rate sixty eight breathing sixteen temperature thirty six point seven oxygen ninety eight percent i sent the walker for repair started stand by help with transfers and her fall risk score went from twelve to fifteen i notified her husband george,8.0,Near-miss by the walker
8,at lunch mr robert smith suddenly grabbed his throat turned red and made no sound i did the heimlich and after three thrusts he coughed up a piece of steak and started breathing he is now sitting up and alert with mild throat soreness his vitals are stable i recommended a soft diet until speech therapy can reassess i notified his family and put in a swallowing assessment referral,9.0,Choking at lunch
9,i was called to the common area for mr harold green who was pacing raising his voice and trying to push a chair confused about the time and place i spoke calmly and walked him to a quiet area then checked for pain hunger and discomfort blood pressure one forty over eighty two heart rate seventy eight breathing eighteen oxygen ninety seven percent no injuries because his urine infections often trigger this i started a urine dipstick i notified his family and will recheck once the lab is back,10.0,Choking at lunch
10,mr richard lee who has dementia and wanders was missing from his room and the common areas we secured the exits and searched the cameras showed him going out the side courtyard door we found him in the parking lot confused but unhurt and brought him back inside a full check showed no injuries and we gave him fluids we updated his wander risk plan added a wanderguard bracelet and increased hourly checks i notified his family,11.0,Choking at lunch
11,humpty dumpty sat on a wall humpty dumpty had a great fall all the king horses and all the king men could not put humpty together again,12.0,Bad Progress Note
12,the crowd is on its feet as the attack builds down the right flank a quick exchange of passes opens space at the edge of the area and the forward strikes first time the goalkeeper gets a hand to it but the rebound falls kindly another effort—goal the stadium erupts as teammates rush in celebration with only minutes remaining this could be the decisive moment in a thrilling contest that has swung from end to end throughout the evening,13.0,Bad Progress Note
13,james carlson age 46 paramedics found him unconscious and bleeding mechanisms of injury are unknown but he has a large sucking chest wound and a wife with very healthy lungs,14.0,Bad Progress Note
14,NaN,NaN,NaN
15,NaN,NaN,NaN
16,NaN,NaN,NaN
17,NaN,NaN,NaN

In [6]:
print(spoken_ref_note['Reference Diagnoses'].iloc[0])

at approximately 19 00 i responded to an emergency call bell near the third floor elevator upon arrival i found mrs jane doe that room number one twenty one eighty two years old lying on her back with a care aide supporting her head the care aide witnessed the fall and reported that the resident was reaching for the elevator button when she lost her balance and fell backward striking the back of her head on the tile floor mrs doe was alert but confused about what happened there was a three centimeter hematoma on the back of her head but no open wounds her glasgow coma scale was thirteen eye response four verbal response four and motor response five i checked her vitals blood pressure was one sixty over ninety heart rate eighty eight respiratory rate eighteen and oxygen saturation ninety six percent on room air i initiated neuro checks every fifteen minutes and gave her 06 00 fifty milligrams of tylenol per standing orders i paged the on call physician but did not get an immediate response since this was a witnessed fall with a head impact i called nine one one for hospital transfer i also notified mrs doe power of attorney that her husband george the resident was transferred to the hospital at seven thirty five pm along with her med administration record recent vitals and her advance directives i have let facility maintenance know to check the lighting in that elevator area i will follow up with the hospital for updates

# Merging Data (Reference Spoken Notes + Hypothesis Notes)

In [6]:
import inspect
print(inspect.getsource(preprocessing_pipeline))

def preprocessing_pipeline(df, column):
    df[column] = df[column].str.lower()  # Decapitalization
    df[column] = df[column].str.replace('\n', ' ')  # Remove newline

    df[column] = df[column].apply(normalize_times)
    #df[column] = df[column].apply(lambda x: re.sub(r'\d+', convert_number_words, x) if isinstance(x, str) else x)


    df[column] = df[column].str.replace('-', ' ')
    df[column] = df[column].str.replace(':', ' ')
    df[column] = df[column].str.replace('/', 'over')
    df[column] = df[column].str.replace(r"'s\b", '', regex=True)
    # Contraction
    df[column] = df[column].apply(contraction)

    # Removal of punctuation
    punc_table = str.maketrans("", "", string.punctuation)
    df[column] = df[column].str.translate(punc_table)

    # Removal of white space
    df[column] = df[column].str.replace(r'\s+', ' ', regex=True)  # Extra white space
    df[column] = df[column].str.strip()  # Trailing white space

    return df

In [31]:
spoken_note_cleaned['Type'] = spoken_note_cleaned['Type'].str.strip()
nurseGPT_transcript_cleaned['Type'] = nurseGPT_transcript_cleaned['Type'].str.strip()

merged_df = pd.merge(spoken_note_cleaned, nurseGPT_transcript_cleaned, on=['Page Number', 'Type'], how='outer')

In [7]:
spoken_note_cleaned = preprocessing_pipeline(spoken_ref_note, 'Reference Diagnoses')
print(spoken_note_cleaned['Reference Diagnoses'].iloc[1])

i found mrs jane doe on the floor by the third floor elevator after a witnessed fall she hit the back of her head on the floor she is awake but confused there is a three centimeter bump on the back of her head with no open cut her blood pressure is one sixty over ninety heart rate eighty eight breathing eighteen oxygen ninety six percent on room air i started neuro checks every fifteen minutes gave tylenol six fifty per standing order paged the doctor called nine one one and notified her husband george

# WER Score Output

In [32]:
def wer_computation(df, ref_col, hyp_col):
    error_score_list =[]
    sub_error_list = []
    del_error_list = []
    insertions_error_list = []
    corr_count_list = []
    
    
    #Extract score
    for ref_text, hyp_text in zip(df[ref_col], df[hyp_col]):
        if pd.isna(ref_text) or pd.isna(hyp_text) is None:
            ref_text = ''
            hyp_text = ''   
        error_report = jiwer.process_words(ref_text, hyp_text)
        error_score = error_report.wer * 100
        sub_error = error_report.substitutions
        del_error = error_report.deletions
        insertions_error = error_report.insertions
        corr_count = error_report.hits

        # Append list
        error_score_list.append(error_score)
        sub_error_list.append(sub_error)
        del_error_list.append(del_error)
        insertions_error_list.append(insertions_error)
        corr_count_list.append(corr_count)

    new_cols = pd.DataFrame({
    'Error Score': error_score_list,
    'Substitution Error Count': sub_error_list,
    'Deletion Error Count': del_error_list,
    'Insertion Error Count': insertions_error_list,
    'Correct Transcribed Word Count': corr_count_list
    })

    df = pd.concat([df, new_cols], axis = 1)
    return df

df_wer_computed = wer_computation(merged_df, 'Reference Diagnoses', 'Hypothesis Diagnoses')
df_wer_computed

,Reference Diagnoses,Page Number,Type,Hypothesis Diagnoses,Error Score,Substitution Error Count,Deletion Error Count,Insertion Error Count,Correct Transcribed Word Count
0,at approximately nineteen zero i responded to an emergency call bell near the third floor elevator upon arrival i found mrs jane doe that room number one twenty one eighty two years old lying on her back with a care aide supporting her head the care aide witnessed the fall and reported that the resident was reaching for the elevator button when she lost her balance and fell backward striking the back of her head on the tile floor mrs doe was alert but confused about what happened there was a three centimeter hematoma on the back of her head but no open wounds her glasgow coma scale was thirteen eye response four verbal response four and motor response five i checked her vitals blood pressure was one sixty over ninety heart rate eighty eight respiratory rate eighteen and oxygen saturation ninety six percent on room air i initiated neuro checks every fifteen minutes and gave her six zero fifty milligrams of tylenol per standing orders i paged the on call physician but did not get an immediate response since this was a witnessed fall with a head impact i called nine one one for hospital transfer i also notified mrs doe power of attorney that her husband george the resident was transferred to the hospital at seven thirty five pm along with her med administration record recent vitals and her advance directives i have let facility maintenance know to check the lighting in that elevator area i will follow up with the hospital for updates,1.0,Fall emergency,at approximately seven of the clock pm i responded to an emergency call bell near the third floor elevator upon arrival i found mrs jane doe that room number one hundred and twenty one eighty two years old lying on her back with a care aide supporting her head the care aide witnessed the fall and reported that the resident was reaching for the elevator button when she lost her balance and fell backward striking the back of her head on the tile floor mrs doe was alert but confused about what happened there was a three centimeter he met oma on the back of her head but no open wounds her glasgow coma scale was thirteen eye response for verbal response for and motor response five i checked her vitals blood pressure was one hundred and sixty over ninety heart rate eighty eight respiratory rate eighteen and oxygen saturation ninety six on room air i initiated neuro checks every fifteen minutes and gave her six hundred and fifty milligrams of tylenol per standing orders i paged the on call physician but did not get an immediate response since this was a witnessed fall with a head impact i called nine hundred and eleven for hospital transfer i also notified mrs doe power of attorney that her husband george the resident was transferred to the hospital at nineteen thirty five along with her med administration record recent vitals and her advance directives i have let facility maintenance know to check the lighting in that elevator area i will follow up with the hospital for updates,8.593750,9,2,11,245
1,i found mrs jane doe on the floor by the third floor elevator after a witnessed fall she hit the back of her head on the floor she is awake but confused there is a three centimeter bump on the back of her head with no open cut her blood pressure is one sixty over ninety heart rate eighty eight breathing eighteen oxygen ninety six percent on room air i started neuro checks every fifteen minutes gave tylenol six fifty per standing order paged the doctor called nine one one and notified her husband george,2.0,Fall with a head injury,i found mrs jane doe on the floor by the third floor elevator after a witnessed fall she hit the back of her head on the floor she is awake but confused there is a three centimeter bump on the back of her head with no open cut her blood pressure is one hundred and sixty over ninety heart rate eighty eight breathing eighteen oxygen ninety six on room air i started neuro checks every fifteen minutes gave tylenol six hundred and fifty per standing order paged the doctor called nine hundred and eleven and notified her husband george,8.421053,2,1,5,92
2,i did a routine morning check on mrs jane doe she is awake and knows where she is a little unsure of the time she looks comfortable her skin is warm dry and intact blood pressure one thirty two over seventy eight heart rate seventy two breathing sixteen temperature thirty six point eight oxygen ninety eight percent she had a normal bowel movement and is walking well with her walker no pain and no concerns,3.0,Routine morning check,i did a routine morning check on mrs jane doe she is awake and knows where she is a little unsure of the time she looks comfortable her skin is warm dry and intact blood pressure one hundred and thirty two over seventy eight heart rate seventy two breathing sixteen temperature thirty sixeight oxygen ninety eight she had a normal bowel movement and is walking well with her walker no pain and no concerns,8.000000,1,3,2,71
3,recording vital signs for mrs jane doe blood pressure one twenty eight over seventy six heart rate seventy breathing sixteen temperature thirty six point seven oxygen ninety seven percent on room air she is comfortable with no complaints,4.0,Vital signs only,recording vital signs for mrs jane doe blood pressure one hundred and twenty eight over seventy six heart rate seventy breathing sixteen temperature thirty sixseven oxygen ninety seven on room air she is comfortable with no complaints,15.789474,1,3,2,34
4,mrs jane doe has pain in both knees from her arthritis worse the last two days especially in the mornings she rates it six out of ten achy and stiff no swelling blood pressure one forty over eighty four heart rate seventy six temperature thirty six point seven oxygen ninety seven percent i gave acetaminophen six fifty per standing order used a warm compress and asked for a physiotherapy referral i notified her family and will check again in four hours,5.0,Knee pain,mrs jane doe has pain in both knees from her arthritis worse the last two days especially in the mornings she rates it six out of ten achy and stiff no swelling blood pressure one hundred and forty over eighty four heart rate seventy six temperature thirty sixseven oxygen ninety seven i gave a seaton oh fin six hundred and fifty per standing order used a warm compress and asked for a physio therapy referral i notified her family and will check again in four hours,17.283951,3,3,8,75
5,mrs jane doe is more short of breath than usual with little activity no chest pain or fever her oxygen is ninety one percent on room air down from ninety five yesterday breathing twenty two and a little labored with wheezing i gave ventolin two puffs with a spacer per order encouraged pursed lip breathing and paged the doctor i notified her family,6.0,Shortness of breath,mrs jane doe is more short of breath than usual with little activity no chest pain or fever her oxygen is ninety one on room air down from ninety five yesterday breathing twenty two and a little labored with wheezing i gave venti lin two puffs with a spacer per order encouraged pursed lip breathing and paged the doctor i notified her family,4.761905,1,1,1,61
6,a care aide found mrs jane doe unresponsive in her wheelchair by the first floor elevator pale and clammy she responded weakly to a sternal rub blood pressure ninety over sixty heart rate one twenty and irregular breathing twenty four oxygen ninety one percent i gave oxygen two liters by nasal cannula and her oxygen came up to ninety four i gave aspirin eighty one per order called the doctor and nine one one she is full code i notified her family,7.0,Found unresponsive,a care aide found mrs jane doe unresponsive in her wheelchair by the first floor elevator pale and clammy she responded weakly to a sternum rub blood pressure ninety over sixty heart rate one hundred and twenty and irregular breathing twenty four oxygen ninety one i gave oxygen two liters by nasal cannula and her oxygen came up to ninety four i gave aspirin eighty one per order called the doctor and nine hundred and eleven i notified her family,12.195122,4,4,2,74
7,a care aide saw mrs jane doe unsteady by the second floor elevator while moving from her walker she is awake and knows where she is a little unsure of the time her walker was set too low with the brake half on she has good shoes and no pain blood pressure one thirty eight over eighty two heart rate sixty eight breathing sixteen temperature thirty six point seven oxygen ninety eight percent i sent the walker for repair started stand by help with transfers and her fall risk score went from twelve to fifteen i notified her husband george,8.0,Near-miss by the walker,a care aide saw mrs jane doe unsteady by the second floor elevator while moving from her walker she is awake and knows where she is a little unsure of the time her walker was set too low with the brake half on she has good shoes and no pain blood pressure one hundred and thirty eight over eighty two heart rate sixty eight breathing sixteen temperature thirty sixseven oxygen ninety eight i sent the walker for repair started standby help with transfers and her fall risk score went from twelve to fifteen i notified her husband george,8.000000,2,4,2,94
8,at lunch mr robert smith suddenly grabbed his throat turned red and made no sound i did the heimlich and after three thrusts he coughed up a piece of steak and started breathing he is now sitting up and alert with mild throat soreness his vitals are stable i recommended a soft diet until speech therapy can reassess i notified his family and put in a swallowing assessment referral,9.0,Choking at lunch,at lunch mr robert smith suddenly grabbed his throat turned red and made no sound i did the heimlick and after three thrusts he coughed up a piece of steak and started breathing he is now sitting up and alert with mild throat soreness his vitals are stable i recommended a soft diet until speech therapy can reassess i notified his family and put in a swallowing assessment referral,1.449275,1,0,0,68
9,i was called to the common area for mr harold green who was pacing raising his voice and trying to push a chair confused about the time and place i spoke calmly and walked him to a quiet area then checked for pain hunger and discomfort blood pressure one forty over eighty two heart rate seventy eight breathing eighteen oxygen ninety seven percent no injuries because his urine infections often trigger this i started a urine dipstick i notified his family and will recheck once the lab is back,10.0,Choking at lunch,i was called to the common area for mr harold green who was pacing raising his voice and trying to push a chair confused about the time and place i spoke calmly and walked him to a quiet area then checked for pain hunger and discomfort blood pressure one hundred and forty over eighty two heart rate seventy eight breathing eighteen oxygen ninety seven no injuries because his urinary infections often trigger this i started a urine dip stick i notified his family and will recheck once the lab is back,6.741573,2,1,3,86
10,mr richard lee who has dementia and wanders was missing from his room and the common areas we secured the exits and searched the cameras showed him going out the side courtyard door we found him in the parking lot confused but unhurt and brought him back inside a full check showed no injuries and we gave him fluids we updated his wander risk plan added a wanderguard bracelet and increased hourly checks i notified his family,11.0,Choking at lunch,mr richard lee who has dementia and wanders was missing from his room and the common areas we secured the exits and searched the cameras showed him going out the side courtyard door we found him in the parking lot confused but unhurt and brought him back inside a full check showed no injuries and we gave him fluids we updated his wander risk plan added a wander guard bracelet and increased hourly checks i notified his family,2.597403,1,0,1,76
11,humpty dumpty sat on a wall humpty dumpty had a great fall all the king horses and all the king men could not put humpty together again,12.0,Bad Progress Note,humpty dumpty sat on a wall humpty dumpty had a great fall all the king horses and all the king men could not put humpty together again,0.000000,0,0,0,27
12,the crowd is on its feet as the attack builds down the right flank a quick exchange of passes opens space at the edge of the area and the forward strikes first time the goalkeeper gets a hand to it but the rebound falls kindly another effort—goal the stadium erupts as teammates rush in celebration with only minutes remaining this could be the decisive moment in a thrilling contest that has swung from end to end throughout the evening,13.0,Bad Progress Note,the crowd is on its feet as the attack builds down the right flank a quick exchange of passes opens space at the edge of the area and the forward strikes first time the goalkeeper gets a hand to it but the rebound falls kindly another effort goal the stadium erupts as teammates rush in celebration with only minutes remaining this could be the decisive moment in a thrilling contest that has swung from end to end throughout the evening,2.531646,1,0,1,78
13,james carlson age forty six paramedics found him unconscious and bleeding mechanisms of injury are unknown but he has a large sucking chest wound and a wife with very healthy lungs,14.0,Bad Progress Note,james carlson age forty six paramedics found him unconscious and bleeding mechanisms of injury are unknown but he has a large sucking chess wound and a wife with very healthy lungs,3.225806,1,0,0,30
14,NaN,NaN,NaN,NaN,0.000000,0,0,0,0
15,NaN,NaN,NaN,NaN,0.000000,0,0,0,0
16,NaN,NaN,NaN,NaN,0.000000,0,0,0,0
17,NaN,NaN,NaN,NaN,0.000000,0,0,0,0

In [33]:
import normalize_time_simple
print(normalize_time_simple.__file__)

from normalize_time_simple import normalize_times
print(normalize_times("at approximately seven o'clock pm i responded"))

c:\Users\Khuong Nguyen\Desktop\NurseGPT Eval\Automation Script\WER_Automation_Script\normalize_time_simple.py
at approximately 19:00 i responded